### PR TITLE
Add Maven caching

### PR DESCRIPTION
**Pull request by viktigpetterr**

### CODE REVIEW

**Comment by viktigpetterr** [comment]
Make sure to add `DEBRICKED_TOKEN` to the repo secrets.

**Review by zozs — APPROVED** [review]
Looks good to me!  @sweoggy needs to add the token though, if not already done, I don't have access :)

**Comment by sweoggy** [comment]
@viktigpetterr can you add a `DEBRICKED_TOKEN` to your own repo as well and retry the pipeline? Just so we can test that everything is working

**Comment by viktigpetterr** [comment]
Sure thing

**Comment by Noxet** [comment]
Updated docs in staging, looks good now!

**Comment by viktigpetterr** [comment]
@sweoggy 
Here it is: 
[ci job](https://github.com/viktigpetterr/example-source-codeless-scan-maven/runs/3721437039?check_suite_focus=true)

**Comment by sweoggy** [comment]
Thanks @viktigpetterr!

**Comment by sweoggy** [comment]
I thought about this now, shouldn't we update the readme to include caching as well? @viktigpetterr

**Comment by viktigpetterr** [comment]
Yeah we should probably put it in there

**Pull request merged**
